---
deployment:
  tasks:
    - echo "Building Angular project..."
    - npm install
    - npm run build -- --configuration=production
    - export DEPLOYPATH=~/public_html/resumemaker
    - echo "Copying built files to $DEPLOYPATH"
    - rm -rf $DEPLOYPATH/*
    - cp -R dist/resume-maker/* $DEPLOYPATH
